
language: java

jdk:
  - oraclejdk8

before_install:
  - curl -s https://api.github.com/repos/vorth/vzome-core/releases/latest > /tmp/latest.json
  - cat /tmp/latest.json
  - export LATEST_ARTIFACT_TAG=$(cat /tmp/latest.json | grep 'tag_name' | head -n 1 | cut -d '"' -f 4)
  - echo $LATEST_ARTIFACT_TAG
  - export LATEST_ARTIFACT_URL=$(cat /tmp/latest.json | grep 'browser_download' | head -n 1 | cut -d '"' -f 4)
  - echo $LATEST_ARTIFACT_URL
  - wget ${LATEST_ARTIFACT_URL} -O /tmp/vzome-core.jar
  - ls -lF /tmp/vzome-core.jar
  - mvn install:install-file -DgroupId=com.vzome.core -Dpackaging=jar -Dversion=${LATEST_ARTIFACT_TAG} -DartifactId=vzome-core -Dfile=/tmp/vzome-core.jar

script: ./gradlew zipWin64Distribution createDmg
