# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: core unit & regression tests

on:
  push:
    paths:
      - 'core/src/main/java/**'
      - 'core/src/regression/**'
      - 'core/src/test/java/**'
      - 'core/build.gradle'
  pull_request:
    paths:
      - 'core/src/main/java/**'
      - 'core/src/regression/**'
      - 'core/src/test/java/**'
      - 'core/build.gradle'
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run unit and regression tests
      run: ./gradlew test regression -PregressionOutput=failures.xml
    - name: Archive regression failures
      uses: actions/upload-artifact@v2
      with:
        name: regression-failures
        path: failures.xml
